baseURL = "/"
languageCode = "fr"
title = "Conso-Score"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo_mobile.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.png"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "Conso-Score - un système d'étiquetage clair et lisible."
    meta_og_title = "Conso-Score"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Conso-Score - un système d'étiquetage clair et lisible."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
    name = "Bienfaits"
    url = "/analysis/"
    weight = 1

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 2

[[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
